Added training data for comets
ritwik12/Celestial-bodies-detection pull request #32
Opened 2019-10-23 13:44 UTC by kousikr26

2019-10-28 12:32 UTC, ritwik12 commented
@kousikr26 Thanks for the training data, are you going to add the code change as well? Please refer to #26 if you need some reference.

2019-10-28 14:50 UTC, kousikr26 commented
@ritwik12 Added the code as well please review

2019-11-04 11:32 UTC, ritwik12 requested changes
Please add test data and also update hub/examples/image_retraining/display_info.yml for the same @kousikr26

2019-11-05 08:23 UTC, kousikr26 commented
@ritwik12 Added test data, the same problem for comets regarding the display_info.yml

2019-11-05 12:13 UTC, ritwik12 commented
@kousikr26 Please remove `comet_2.jpg` as test data should not be in training data and `comet_3.jpg`is having text on image which will be a NOISE for classification. 
Also please check that test data and training data are not common and all images are real and not computarised. For `image_5 .jpg` also it will look more like a meteor as it is zoomed image.

2026-02-26 19:48 UTC, closed without merging