Irregular galaxy
ritwik12/Celestial-bodies-detection pull request #33
Opened 2019-10-23 13:54 UTC by kousikr26

2019-10-28 12:36 UTC, ritwik12 commented
@kousikr26 Thanks for the PR but this includes some images of comets as well. I guess you are creating branches from other branches only. You should keep a branch clean such as "master" to create as many new branches for all the Different PRs unrelated to each other.

2019-10-28 14:57 UTC, kousikr26 commented
@ritwik12 sorry about that removed it now and added the necessary code, please review

2019-11-04 11:29 UTC, ritwik12 commented
@kousikr26 Can you please add few test data also for this?

2019-11-04 11:31 UTC, ritwik12 requested changes
Also, please update `hub/examples/image_retraining/display_info.yml` for the same

2019-11-04 13:08 UTC, kousikr26 commented
@ritwik12 What info should I put in the display_info.yml file for an irregular galaxy as there is no such quantitative data about them. I didn't add anything as there was no entry in it for spiral and elliptical galaxy also.

2019-11-04 13:12 UTC, ritwik12 commented
@kousikr26 Not needed in that case, we should have an issue for adding display info data for galaxies as well to get more info. I will create it

2019-11-04 13:13 UTC, ritwik12 commented
@kousikr26 Please add test data.

2019-11-05 08:19 UTC, kousikr26 commented
@ritwik12 added test data

2019-11-05 12:17 UTC, ritwik12 commented
@kousikr26 `irregular_3.jpg` seems doubtful to be real, better remove it. Two images are fine for test data. Also, where did you get the data. Google search or most websites will not be able to identify a spiral, elliptical or irregular galaxy and all pics will be mixed up which I can see in your data. Please manually verify all data is real and irregular galaxy only. Few are elliptical in this.

2026-02-26 19:49 UTC, closed without merging