Added Asteroids Dataset
ritwik12/Celestial-bodies-detection pull request #72
Opened 2020-10-24 10:52 UTC by Zignake

Resolving the Issue: https://github.com/ritwik12/Celestial-bodies-detection/issues/41

2020-10-27 19:59 UTC, ritwik12 requested changes

2020-10-27 19:59 UTC, ritwik12 commented on hub/examples/image_retraining/label_image.py
> +    elif ans == 'asteroid':
@Zignake This will be asteroids

```suggestion
    elif ans == 'asteroids':
```

2020-10-28 19:17 UTC, ritwik12 approved these changes

2020-10-28 19:17 UTC, merged

2020-10-28 19:59 UTC, ritwik12 commented
@Zignake Thanks!!

2020-11-06 06:32 UTC, Zignake commented
> @Zignake Thanks!!

Also, i guess you had forgotten to add the hacktober-fest accepted tag to this PR. Can you do anything about it now?

2020-11-07 20:23 UTC, ritwik12 commented
@Zignake It was not needed if a PR is merged and I merged your PR in time. I am adding that Label now if it helps somehow.